services:
  db:
    container_name: postgres
    environment:
      POSTGRES_USER: Navire_DB
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    Restart: unless_stopped

  network:
    db:
  volume:
    db:
